### ISSUE TITLE
line 13

### ISSUE THREAD

**Issue by rabia-aaziz** [sarariazahmedkhan/TK-Task-01-C.V#2]
The center element is obsolete 
 Use CSS instead. <center>

**Comment by sarariazahmedkhan** [comment]
line 13 #2 solve

**Comment by sarariazahmedkhan** [comment]
#4 solve..is ka mockup nahi nahi

**Comment by sarariazahmedkhan** [comment]
#1 solve line 35

**Comment by rabia-aaziz** [comment]
issue aapko close nahi krnay
